11_Rails_Intro_Controller/code_along/bookazon/config/routes.rb
Rails.application.routes.draw do
  resources 'books'
  get 'static_pages/home'

  root 'static_pages#home'

end

11_Rails_Intro_Controller/code_along/bookazon/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id             :integer          not null, primary key
#  title          :string
#  year_published :integer
#  author         :string
#  available      :boolean
#  genre          :string
#  image_url      :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Book < ActiveRecord::Base
end

11_Rails_Intro_Controller/code_along/bookazon/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

11_Rails_Intro_Controller/code_along/bookazon/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # views always have access to instance vars

  # make the view have access to all books
  def index
    @books = Book.all
  end

  def show

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def book_params

  end

end

11_Rails_Intro_Controller/code_along/bookazon/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

11_Rails_Intro_Controller/code_along/bookazon/app/helpers/application_helper.rb
module ApplicationHelper
end

11_Rails_Intro_Controller/code_along/bookazon/app/helpers/books_helper.rb
module BooksHelper
end

11_Rails_Intro_Controller/code_along/bookazon/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

11_Rails_Intro_Controller/code_along/bookazon/app/views/books/edit.html.erb
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

11_Rails_Intro_Controller/code_along/bookazon/app/views/books/index.html.erb
<div class="col-12">
  <h1>Our Book Collection</h1>

  <div class="well">
    <% @books.each do |book| %>
      <ul><%= book.title %></ul>
    <% end %>
  </div>
</div>

11_Rails_Intro_Controller/code_along/bookazon/app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

11_Rails_Intro_Controller/code_along/bookazon/app/views/books/show.html.erb
<h1>Books#show</h1>
<p>Find me in app/views/books/show.html.erb</p>

11_Rails_Intro_Controller/code_along/bookazon/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookazonApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

11_Rails_Intro_Controller/code_along/bookazon/app/views/static_pages/home.html.erb
<h1>Welcome to bookazon</h1>
<p> the best place for cool books</p>
<%= link_to 'checkout our books', books_path, class: 'btn btn-lg btn-danger' %>